# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'project2.ui'
#
# Created by: PyQt5 UI code generator 5.15.4
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(861, 858)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(160, 10, 531, 51))
        self.label.setStyleSheet("color: rgb(0, 85, 127);\n"
"background-color: rgb(255, 255, 255);\n"
"font: 75 italic 24pt \"Noto Sans\";\n"
"text-decoration: underline;")
        self.label.setObjectName("label")
        self.alp = QtWidgets.QLineEdit(Form)
        self.alp.setGeometry(QtCore.QRect(210, 250, 241, 31))
        self.alp.setObjectName("alp")
        self.alb = QtWidgets.QLineEdit(Form)
        self.alb.setGeometry(QtCore.QRect(210, 200, 241, 31))
        self.alb.setObjectName("alb")
        self.sex_2 = QtWidgets.QLineEdit(Form)
        self.sex_2.setGeometry(QtCore.QRect(210, 150, 241, 31))
        self.sex_2.setObjectName("sex_2")
        self.age_2 = QtWidgets.QLineEdit(Form)
        self.age_2.setGeometry(QtCore.QRect(210, 100, 241, 31))
        self.age_2.setObjectName("age_2")
        self.pushButton = QtWidgets.QPushButton(Form)
        self.pushButton.setGeometry(QtCore.QRect(340, 700, 141, 31))
        self.pushButton.setStyleSheet("color: rgb(255, 0, 255);\n"
"background-color: rgb(170, 255, 127);\n"
"font: 75 16pt \"Rockwell\";")
        self.pushButton.setObjectName("pushButton")
        self.result = QtWidgets.QLabel(Form)
        self.result.setGeometry(QtCore.QRect(40, 780, 691, 51))
        self.result.setStyleSheet("color: rgb(170, 0, 0);\n"
"font: 75 16pt \"Noto Naskh Arabic\";")
        self.result.setObjectName("result")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(70, 90, 111, 51))
        self.label_6.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_6.setObjectName("label_6")
        self.alt = QtWidgets.QLineEdit(Form)
        self.alt.setGeometry(QtCore.QRect(210, 300, 241, 31))
        self.alt.setObjectName("alt")
        self.ast = QtWidgets.QLineEdit(Form)
        self.ast.setGeometry(QtCore.QRect(210, 350, 241, 31))
        self.ast.setObjectName("ast")
        self.bil = QtWidgets.QLineEdit(Form)
        self.bil.setGeometry(QtCore.QRect(210, 400, 241, 31))
        self.bil.setObjectName("bil")
        self.che = QtWidgets.QLineEdit(Form)
        self.che.setGeometry(QtCore.QRect(210, 450, 241, 31))
        self.che.setObjectName("che")
        self.chol = QtWidgets.QLineEdit(Form)
        self.chol.setGeometry(QtCore.QRect(210, 500, 241, 31))
        self.chol.setObjectName("chol")
        self.crea = QtWidgets.QLineEdit(Form)
        self.crea.setGeometry(QtCore.QRect(210, 550, 241, 31))
        self.crea.setObjectName("crea")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(70, 140, 91, 51))
        self.label_7.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(70, 190, 121, 51))
        self.label_8.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(70, 240, 141, 51))
        self.label_9.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(70, 290, 141, 51))
        self.label_10.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(70, 340, 141, 51))
        self.label_11.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(80, 390, 141, 51))
        self.label_12.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(Form)
        self.label_13.setGeometry(QtCore.QRect(60, 440, 141, 51))
        self.label_13.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(Form)
        self.label_14.setGeometry(QtCore.QRect(40, 490, 141, 51))
        self.label_14.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(Form)
        self.label_15.setGeometry(QtCore.QRect(40, 540, 141, 51))
        self.label_15.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(Form)
        self.label_16.setGeometry(QtCore.QRect(60, 590, 141, 51))
        self.label_16.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_16.setObjectName("label_16")
        self.ggt = QtWidgets.QLineEdit(Form)
        self.ggt.setGeometry(QtCore.QRect(210, 600, 241, 31))
        self.ggt.setObjectName("ggt")
        self.prot = QtWidgets.QLineEdit(Form)
        self.prot.setGeometry(QtCore.QRect(210, 650, 241, 31))
        self.prot.setObjectName("prot")
        self.label_17 = QtWidgets.QLabel(Form)
        self.label_17.setGeometry(QtCore.QRect(40, 640, 141, 51))
        self.label_17.setStyleSheet("color: rgb(255, 170, 0);\n"
"font: 75 20pt \"Sitka Small\";")
        self.label_17.setObjectName("label_17")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "project2"))
        self.label.setText(_translate("Form", "Predict Hepatitis Reason Type"))
        self.pushButton.setText(_translate("Form", "Predict"))
        self.result.setText(_translate("Form", "Result :"))
        self.label_6.setText(_translate("Form", "Age :"))
        self.label_7.setText(_translate("Form", "Sex :"))
        self.label_8.setText(_translate("Form", "ALB :"))
        self.label_9.setText(_translate("Form", "ALP :"))
        self.label_10.setText(_translate("Form", "ALT :"))
        self.label_11.setText(_translate("Form", "AST :"))
        self.label_12.setText(_translate("Form", "BIL :"))
        self.label_13.setText(_translate("Form", "CHE :"))
        self.label_14.setText(_translate("Form", "CHOL :"))
        self.label_15.setText(_translate("Form", "CREA :"))
        self.label_16.setText(_translate("Form", "GGT :"))
        self.label_17.setText(_translate("Form", "PROT :"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
